const REQUIRED_FIELD_MESSAGE = "Campo obrigatório";
const PASSWORD_MESSAGES_NOT_MATCH = "As senhas não correspondem";
const PASSWORD_MIN_LENGTH_MESSAGE = "Sua senha deve ter pelo menos 8 dígitos";
const EMAIL_INVALID_MESSAGE = "Email inválido";
const CPF_INVALID_MESSAGE = "CPF inválido";
const PHONE_INVALID_MESSAGE = "Telefone inválido";
const BIRTH_DATE_INVALID_MESSAGE = "Data inválida";
const NAME_MIN_MESSAGE = "O nome está muito curto";
const DESCRIPTION_MIN_MESSAGE = "A descrição está muito curta";
const ANSWER_MIN_MESSAGE = "A resposta está muito curta";
const MIN_PASSWORD_LENGTH = 8;
const FILE_MAX_SIZE_MESSAGE =
  "Arquivo muito grande. O arquivo deve ter no máximo ";
const FILE_TYPE_UNSUPPORTED_MESSAGE =
  "Formato inválido. Forneça um arquivo do tipo  ";
const NAVIGATION_TIMER = 1000;
const PRIMARY_COLOR = "#0267FF";
const MAX_CONTENT_LENGTH_MESSAGE =
  "Conteúdo está excendo a quantidade máxima de caracteres permitidos";

const ITEMS_PER_PAGE_OPTIONS = [
  { value: 10, label: "10" },
  { value: 20, label: "20" },
  { value: 50, label: "50" },
  { value: 100, label: "100" },
];

const MAX_TRAININGS_CREATION_ALLOWED_GOLD_PLAN = parseInt(
  import.meta.env.VITE_MAX_TRAININGS_CREATION_ALLOWED_GOLD_PLAN
);
const MAX_TRAININGS_CREATION_ALLOWED_PLATINUM_PLAN = parseInt(
  import.meta.env.VITE_MAX_TRAININGS_CREATION_ALLOWED_PLATINUM_PLAN
);
const MAX_TRAININGS_CREATION_ALLOWED_DIAMOND_PLAN = parseInt(
  import.meta.env.VITE_MAX_TRAININGS_CREATION_ALLOWED_DIAMOND_PLAN
);

export {
  ANSWER_MIN_MESSAGE,
  BIRTH_DATE_INVALID_MESSAGE,
  CPF_INVALID_MESSAGE,
  DESCRIPTION_MIN_MESSAGE,
  EMAIL_INVALID_MESSAGE,
  FILE_MAX_SIZE_MESSAGE,
  FILE_TYPE_UNSUPPORTED_MESSAGE,
  ITEMS_PER_PAGE_OPTIONS,
  MAX_CONTENT_LENGTH_MESSAGE,
  MAX_TRAININGS_CREATION_ALLOWED_DIAMOND_PLAN,
  MAX_TRAININGS_CREATION_ALLOWED_GOLD_PLAN,
  MAX_TRAININGS_CREATION_ALLOWED_PLATINUM_PLAN,
  MIN_PASSWORD_LENGTH,
  NAME_MIN_MESSAGE,
  NAVIGATION_TIMER,
  PASSWORD_MESSAGES_NOT_MATCH,
  PASSWORD_MIN_LENGTH_MESSAGE,
  PHONE_INVALID_MESSAGE,
  PRIMARY_COLOR,
  REQUIRED_FIELD_MESSAGE,
};
